# Imagen base con Node
FROM node:20

# Seteamos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos solo package.json y lock para instalar dependencias primero
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]
